### ISSUE TITLE
Add pace to the portal.

### ISSUE THREAD

**Issue by kushagra12** [IEEECS-VIT/portals#13]
We can add this http://github.hubspot.com/pace/docs/welcome/ to our site so RnR team doesn't do clicks on the portal like they are playing a CoD game.

**Comment by kushagra12** [comment]
Guys??

**Comment by saurabhmathur96** [comment]
We currently have similar functionality implemented with ng-disabled. 
On click - disable button, Ajax call
On Ajax call complete - enable button

However,  pace provides a better way to do the same. This can be considered for future views and refactoring.

**Comment by ayushagarwal95** [comment]
@saurabhmathur96, @kushagra12, decide on this and finish it.
