### ISSUE TITLE
Pre-commit hooks

### ISSUE THREAD

**Issue by kunagpal** [IEEECS-VIT/portals#2]
Use the module [pre-commit](https://www.npmjs.com/package/pre-commit) to add custom pre-commit git hooks, so that tests may be invoked automatically before every commit.

**Comment by aneesh-neelam** [comment]
Just set up Travis or Semaphore Continuous Integration.

**Comment by kunagpal** [comment]
For the purposes of this application, all three are equivalent.

**Comment by aneesh-neelam** [comment]
Semaphore or Travis use Git hooks anyway.
