### ISSUE TITLE
Perpetuity

### ISSUE THREAD

**Issue by kunagpal** [IEEECS-VIT/portals#4]
Use [forever](https://www.npmjs.com/package/forever) to enable automatic application restarts in case of crash.

**Comment by aneesh-neelam** [comment]
This is not necessary, Heroku already does exponential backoff when starting up crashed processes.

**Comment by kunagpal** [comment]
Exactly, exponential. This is to avoid the exponential time window altogether.

**Comment by saurabhmathur96** [comment]
We are using pm2 to run the app.
