### ISSUE TITLE
Parallelize application middleware loading.

### ISSUE THREAD

**Issue by kunagpal** [IEEECS-VIT/portals#5]
Parallelize all app.use(...) middleware calls to speed up requests.

**Comment by aneesh-neelam** [comment]
app.use(...) in app.js is only called once, on startup.

**Comment by kunagpal** [comment]
Yes, they are. However, parallelizing request middleware has yielded more tightly consistent request response times.

**Comment by saurabhmathur96** [comment]
Do you mean using something like [middleware-flow](https://www.npmjs.com/package/middleware-flow) ?

**Comment by kunagpal** [comment]
No, you don't need to bloat your application's startup routine with unnecessary modules. Use `async.each` within a single middle ware invocation, like [so](https://github.com/IEEECS-VIT/GPL/blob/master/app.js#L86#L87).
